Style/FrozenStringLiteralComment:
  Enabled: false
Documentation:
  Enabled: false
Metrics/BlockLength:
  Enabled: true
  Max: 15
Style/StringLiterals:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
